### ISSUE TITLE
in myStyles.css - use @media for dynamic font-sizes

### ISSUE THREAD

**Issue by kevingovaerts** [deformartin/portfolio#1]
use @media querries to determine the font-sizes for small screen sizes. 
On line 472 there is a media querry which is the same as the media querry whole the way on the bottom of the file - they should be merged. 
Also @media querries always should be on the bottom of the .css file. 
If they are somewhere in the middle, they wont affect styles which are declared, lower then the media querry. 
the idea is that all 'normal' styles get declared on the top, and then underneat you start with @media-querries which affect previous declared styles. 
[https://www.w3schools.com/css/css_rwd_mediaqueries.asp](url)

/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 600px) {...}

/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 600px) {...}

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) {...}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 992px) {...}

/* Extra large devices (large laptops and desktops, 1200px and up) */
@media only screen and (min-width: 1200px) {...}

**Comment by deformartin** [comment]
Thanks for the info, problem fixed.Thanks
